version: "3.10"

services:
  # server
  fastapi-server:
    container_name: fastapi-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app

  # nginx
  fastapi-nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - fastapi-server

  # db
  fastapi-db:
    container_name: fastapi-db
    image: postgres:16.1-alpine3.19
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./fastapi_db:/var/lib/postgresql/data
